### ISSUE TITLE
No Download Links of Required Libraries To Successfully Compile The Program For Windows 9x/ME Given

### ISSUE THREAD

**Issue by nix-enthusiast** [rust9x/rust9x-sample#2]
Hi,

README.md indicates 

> Update the lib paths in .cargo/config.toml to match yours 

And Rust9X wiki states that Visual C++ 2003 toolset is needed to compile programs for Windows 95.

However the download source Visual C++ 2003 toolset (which contains the lib path required for this sample app to work in Windows 95) is not mentioned neither here nor the wiki.

Could you add a link of it? Because it seems that there's no site provides this toolset.

**Comment by seritools** [comment]
VC++ it is not free software and I don't have the rights to distribute it. I would rather not link to gray-area abandonware pages or similar, but that's probably where you can find a download for VC++ 2003.

I installed it myself in a VM and just copied out the required folders from the installation.


If you're fine with increasing the minimum to Windows 98, you might also be able to find Visual C++ 2005 Express Edition somewhere, which was freely released at some point, and use its toolset instead.

Another possible way could be using the [Windows/Platform SDK](https://en.wikipedia.org/wiki/Microsoft_Windows_SDK), though I haven't tested that myself (not sure it has everything you need). It _does_ have download links in the Wikipedia article.

**Comment by nix-enthusiast** [comment]
> VC++ it is not free software and I don't have the rights to distribute it. I would rather not link to gray-area abandonware pages or similar, but that's probably where you can find a download for VC++ 2003.
> 
> I installed it myself in a VM and just copied out the required folders from the installation.
> 
> 
> If you're fine with increasing the minimum to Windows 98, you might also be able to find Visual C++ 2005 Express Edition somewhere, which was freely released at some point, and use its toolset instead.
> 
> Another possible way could be using the [Windows/Platform SDK](https://en.wikipedia.org/wiki/Microsoft_Windows_SDK), though I haven't tested that myself (not sure it has everything you need). It _does_ have download links in the Wikipedia article.

Thanks for the response. Can I ask if the VC versions earlier than VC 7.1 (like 6.x) work for 95?

**Comment by seritools** [comment]
I haven't tested with VC6 for a long time, but:

> Way earlier in the project I've tested VC6 (Visual C++ 6.0 SP6), which also worked somewhat fine after adding unicows.lib from a later toolset/platform SDK.

Feel free to test and report how it's going!

**Comment by nix-enthusiast** [comment]
> I haven't tested with VC6 for a long time, but:
> 
> > Way earlier in the project I've tested VC6 (Visual C++ 6.0 SP6), which also worked somewhat fine after adding unicows.lib from a later toolset/platform SDK.
> 
> Feel free to test and report how it's going!

Of course! I will write it down here (or open a new issue).
